version: '3'

services:
  db: 
    image: postgres
    container_name: law-modeling-db
    ports:
      - 5432:5432
    env_file:
      - ./env/dev.env

  neo4j:
    image: neo4j
    container_name: law-modeling-graph

    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_AUTH=none
    # env_file:
    #   - ./env/dev.env
    # volumes:
    #   - ./data:/data
    volumes:
      - ./docker/graph/plugins:/var/lib/neo4j/plugins
      - ./docker/graph/data:/data/rdf
    command: ["echo","dbms.unmanaged_extension_classes=n10s.endpoint=/rdf",">>","/var/lib/neo4j/conf/neo4j.conf","&&","neo4j", "restart"]


  cache:
    image: redis
    container_name: law-modeling-cache
    ports:
      - 6379:6379