"""test env

Revision ID: 08a50c7232bd
Revises: bd99e2d3bc5c
Create Date: 2022-09-29 22:19:43.504979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a50c7232bd'
down_revision = 'bd99e2d3bc5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
