"""Add column title

Revision ID: 24751716afcc
Revises: b17b7f17513c
Create Date: 2022-09-29 16:23:28.025269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24751716afcc'
down_revision = 'b17b7f17513c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'title')
    # ### end Alembic commands ###
