"""[TEST]env

Revision ID: 7cf85c1e9f83
Revises: c3bba93df3f2
Create Date: 2022-09-29 22:48:17.038795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf85c1e9f83'
down_revision = 'c3bba93df3f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
