"""Add column title

Revision ID: 824b97b429b6
Revises: 24751716afcc
Create Date: 2022-09-29 16:26:03.024916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '824b97b429b6'
down_revision = '24751716afcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
