"""Add column title

Revision ID: bd99e2d3bc5c
Revises: 824b97b429b6
Create Date: 2022-09-29 16:27:01.397576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd99e2d3bc5c'
down_revision = '824b97b429b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
