"""[TEST]env

Revision ID: c3bba93df3f2
Revises: 6fc822b92864
Create Date: 2022-09-29 22:41:16.245160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3bba93df3f2'
down_revision = '6fc822b92864'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
