"""[TEST]env 1

Revision ID: d6559d790595
Revises: 7cf85c1e9f83
Create Date: 2022-09-29 22:51:26.340334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6559d790595'
down_revision = '7cf85c1e9f83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
